### PR TITLE
Upgraded lots of things to match recent changes in the ecosystem

### PR DESCRIPTION
**Pull request by nebrius**
I know this is big, but there's a couple of reasons for it. This all stems from https://github.com/nebrius/raspi-io/issues/91 ultimately, which caused me to shift raspi, raspi-gpio, and raspi-pwm to use pigpio instead of Wiring Pi. This caused pigpio to get out of sync between the modules though, so I needed to upgrade here. While I was at it, I went ahead and upgrade the build system and converted the project to TypeScript to make it inline with the rest of Raspi.js. This allows me to use a lot of code from raspi-pwm here, and vice versa, and they now share some code between them. I also update some of the function signatures to match, so this module is now (in theory) a drop-in replacement for raspi-pwm in existing code.

### CODE REVIEW

**Comment by tralves** [comment]
@nebrius Wow, that is a lot of work. I think it is the best interest of the raspi ecosystem to move this project to your account, don't you agree?

You are much more suited to maintain the project, specially after this re-write. Keeping me as the maintainer will only create another barrier for future development.

You could "un-fork" this project like this: http://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting/41486339#41486339.

Thanks!

**Comment by nebrius** [comment]
@tralves hmm...yeah, I guess that would make sense to move it. Can you add me as a collaborator on the npm package so I can publish too?

I followed the instructions you linked to and set up the new repo, and added you as a collaborator. I never knew you could do that with git, that's a really cool trick!

FWIW, it actually wasn't very much work because almost all of the changes were copy-pasted from the other raspi-* repos :).

**Comment by tralves** [comment]
@nebrius I added you as collaborator in the npm package. Do I need to do anything else?

The biggest problem is that I don't have time to maintain this project anymore, as my interests shifted and my RPi is turned off for months now. I am accepting this PR without testing and will change the README.md to point to the new repo.

Thanks for all the support! I learned a lot in the process!

**Comment by nebrius** [comment]
Thanks @tralves! This is completely up to you of course, but you might consider deleting this repo and forking my new copy to avoid confusion (essentially reversing the fork direction we had earlier).

No worries about running out of time, it happens to the best of us. My GitHub repo is littered with half-finished projects 😄.

I'm glad you learned a lot, and thank you for creating this module to begin with! It started the catalyst for me to convert raspi-gpio and raspi-pwm to also use pigpio over the last few days, which gave me a huge leg up on solving https://github.com/nebrius/raspi-io/issues/91 quickly, which is the first time Raspi IO has flat out been broken in production. Seriously, thank you!

**Pull request merged**
