### PR TITLE
Adds `range` read-only instance property

### PR DESCRIPTION
**Pull request by andrewn**
This adds a read-only property of `range` to instances of SoftPWM e.g.

```js
var softPWM = new SoftPWM({pin: 'P1-26', range: 100, frequency: 200});

console.log(softPWM.range);  // outputs 100
```

This is useful as it's the same property that the `raspi-pwm` module uses. This helps them to be used a bit more interchangeably in Raspi-io.

### CODE REVIEW

**Comment by tralves** [comment]
@andrewn Awesome! Thanks for the PR! Latter I will create and publish a new version of the npm package.

**Comment by andrewn** [comment]
Thanks for the quick response!

Could you post a comment here when the new version is released on NPM please?

**Comment by tralves** [comment]
@andrewn Sure!

**Comment by andrewn** [comment]
Sorry to be annoying but do you a rough idea of when you plan to release? I have a pull request for Raspi-io that relies on this change being published. 

No worries if you're busy, I can always submit the PR but link to the github version of the module on NPM.

**Comment by tralves** [comment]
Done!
Again, thanks for the PR!

**Pull request merged**
